spring.application.name=backendPet

# ===== MySQL =====
spring.datasource.url=jdbc:mysql://localhost:3306/PetConnectRes?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto (cambialo si 8080 esta ocupado)
server.port=8081
